apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-automation-demo
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: svitlana-test
    notifications.argoproj.io/subscribe.on-deployed.slack: svitlana-test
    notifications.argoproj.io/subscribe.on-sync-failed.slack: svitlana-test
    notifications.argoproj.io/subscribe.on-health-degraded.slack: svitlana-test
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: svitlana-test
    notifications.argoproj.io/subscribe.on-sync-status-running.slack: svitlana-test
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: chart
    repoURL: https://github.com/SvitlanaDiach/demo-cicd-automation-app.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
